version: '3.7'

services:
  my-backend:
    platform: linux/x86_64
    image: asia.gcr.io/classproject-347010/class_backend:4.0.2
    build:
      context: .
      dockerfile: Dockerfile
    # env_file:
    #   - ./.env.prod
    # volumes:
    #   - ./src:/myfolder/src
    ports:
      - 3000:3000

  # my-database:
  #   platform: linux/x86_64
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: 'mydocker02'
  #     MYSQL_ROOT_PASSWORD: 'root'
  #   ports:
  #     - 3306:3306

#docker-compose -f docker-compose.prod.yaml build