version: "3.7"

services:
  my_backend:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./index.js:/my_backend/index.js
    ports:
      - 3000:3000

  my_database:
    image: mongo:latest
    ports:
      - 27017:27017
