---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "mysql-k8s-class-config-0uh6"
  namespace: "default"
  labels:
    app: "mysql-k8s-class"
data:
  MYSQL_DATABASE: "mypodclass"
  MYSQL_ROOT_PASSWORD: "root"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "mysql-k8s-class"
  namespace: "default"
  labels:
    app: "mysql-k8s-class"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "mysql-k8s-class"
  template:
    metadata:
      labels:
        app: "mysql-k8s-class"
    spec:
      containers:
        - name: "mysql-1"
          image: "mysql:latest"
          env:
            - name: "MYSQL_DATABASE"
              valueFrom:
                configMapKeyRef:
                  key: "MYSQL_DATABASE"
                  name: "mysql-k8s-class-config-0uh6"
            - name: "MYSQL_ROOT_PASSWORD"
              valueFrom:
                configMapKeyRef:
                  key: "MYSQL_ROOT_PASSWORD"
                  name: "mysql-k8s-class-config-0uh6"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "mysql-k8s-class-hpa-1kis"
  namespace: "default"
  labels:
    app: "mysql-k8s-class"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "mysql-k8s-class"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        targetAverageUtilization: 80
